name: CI & Deploy (python3)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: Run unit tests (python3)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies (python3)
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi

      - name: Run tests (unittest)
        run: python3 -m unittest discover -s tests -p "test_*.py" -v